# Generated by Django 4.2 on 2023-04-12 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade_Orcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('km', models.PositiveBigIntegerField()),
                ('tipo', models.CharField(max_length=255)),
                ('linha', models.CharField(max_length=255)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidade_veiculo', to='abastecimento.unidade_orcamentaria')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Álcool', 'Álcool'), ('Diesel', 'Diesel')], max_length=255)),
                ('quantidade_combustivel', models.PositiveBigIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('abastecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='abastecimento.abastecimento')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculo_item', to='abastecimento.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_original', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidade_contrato', to='abastecimento.unidade_orcamentaria')),
            ],
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastecimento.contrato'),
        ),
    ]
